#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 0
bspc config bottom_padding 35
bspc config right_padding 2
bspc config right_padding 2


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a RobloxPlayerBeta.exe state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config normal_border_color 	"#8AADF4"
bspc config active_border_color 	"#8AADF4"
bspc config focused_border_color "#b4befe"

#
# Autostart
#
# Bar
~/.config/polybar/bar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
 picom -b &
# Flameshot
flameshot
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# notifs
~/.config/bspwm/scripts/playerctlNotify.py
